services:
  cloudflared:
    image: cloudflare/cloudflared:2026.8.2
    container_name: ${CONTAINER_NAME}
    restart: always
    command: tunnel --no-autoupdate run --token ${CFD_TOKEN}
    labels:  
      createdBy: "Apps"
