name: dkturbo
services:
  dkturbo:
    image: registry.cn-shenzhen.aliyuncs.com/cp0204/dkturbo:main
    container_name: dkturbo
    hostname: dkturbo
    volumes:
      - /etc/docker:/etc/docker
      - /opt:/opt
    environment:
      - MODE=registry
      - REGISTRY=${REGISTRY}
    network_mode: bridge
    restart: unless-stopped
    pid: host
    privileged: true
    deploy:
      resources:
        reservations:
          memory: 8M